INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (1,'Centre Ville','21548,7');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (2,'Bellevue - Chantenay - Sainte Anne','22597,3');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (3,'Dervallières - Zola','4403,09');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (4,'Hauts Pavés - Saint Félix','30522,9');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (5,'Malakoff - Saint-Donatien','28078,6');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (6,'Ile de Nantes','32398,2');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (7,'Breil - Barberie','16718,2');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (8,'Nantes Nord','22945,8');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (9,'Nantes Erdre','31816,2');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (10,'Doulon - Bottière','48780,2');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (11,'Nantes Sud','15508,3');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14301,'Trentemoult','7854,51939');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14302,'Hôtel de Ville','4808,84936');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14303,'Château de Rezé','6371,53907');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14304,'Pont Rousseau','7628,89349');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14305,'La Houssais','9288,95165');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14306,'Blordière','4688,33283');
INSERT INTO Quartier (idQuartier,nomQuartier, longueurPiste) VALUES (14307,'Ragon','13172,9418');
